"""
Central Python Registry for GST Reconciliation Types.
Defines metadata, file definitions, column requirements, and metric labels for all 7 engines.
"""
from typing import Dict, List, Any

RECONCILIATION_TYPES = {
    "gstr2b_pr": {
        "id": "gstr2b_pr",
        "name": "GSTR-2B ↔ Purchase Register",
        "short_title": "GSTR-2B vs PR",
        "category": "itc",
        "category_label": "ITC Reconciliation",
        "level": "invoice",
        "file1_label": "Purchase Register",
        "file2_label": "GSTR-2B",
        "financial_metric_label": "Potential ITC at Risk",
        "party_label": "Supplier",
        "parties_label": "Suppliers",
    },
    "gstr2a_gstr2b": {
        "id": "gstr2a_gstr2b",
        "name": "GSTR-2A ↔ GSTR-2B",
        "short_title": "GSTR-2A vs GSTR-2B",
        "category": "itc",
        "category_label": "ITC Reconciliation",
        "level": "invoice",
        "file1_label": "GSTR-2A",
        "file2_label": "GSTR-2B",
        "financial_metric_label": "ITC Timing & Cutoff Difference",
        "party_label": "Supplier",
        "parties_label": "Suppliers",
    },
    "ims_gstr2b": {
        "id": "ims_gstr2b",
        "name": "IMS ↔ GSTR-2B",
        "short_title": "IMS vs GSTR-2B",
        "category": "itc",
        "category_label": "ITC Reconciliation",
        "level": "invoice",
        "file1_label": "IMS Action File",
        "file2_label": "GSTR-2B",
        "financial_metric_label": "Pending / Rejected ITC Impact",
        "party_label": "Supplier",
        "parties_label": "Suppliers",
    },
    "gstr1_sales_register": {
        "id": "gstr1_sales_register",
        "name": "GSTR-1 ↔ Sales Register",
        "short_title": "GSTR-1 vs Sales Register",
        "category": "sales",
        "category_label": "Sales Reconciliation",
        "level": "invoice",
        "file1_label": "Sales Register",
        "file2_label": "GSTR-1",
        "financial_metric_label": "Sales Reporting Difference",
        "party_label": "Customer",
        "parties_label": "Customers",
    },
    "gstr3b_gstr1": {
        "id": "gstr3b_gstr1",
        "name": "GSTR-3B ↔ GSTR-1",
        "short_title": "GSTR-3B vs GSTR-1",
        "category": "returns",
        "category_label": "Return Reconciliation",
        "level": "summary",
        "file1_label": "GSTR-1 Outward Summary",
        "file2_label": "GSTR-3B Tax Liability",
        "financial_metric_label": "Tax Liability Difference (Rule 88C)",
        "party_label": "Section",
        "parties_label": "Return Sections",
    },
    "gstr9_books": {
        "id": "gstr9_books",
        "name": "GSTR-9 ↔ Books",
        "short_title": "GSTR-9 vs Books",
        "category": "annual",
        "category_label": "Annual & Audit Reconciliation",
        "level": "summary",
        "file1_label": "Audited Financials / Books",
        "file2_label": "GSTR-9 Annual Return",
        "financial_metric_label": "Annual Turnover & Tax Variance",
        "party_label": "Ledger",
        "parties_label": "Audit Heads",
    },
    "gstr9c_books": {
        "id": "gstr9c_books",
        "name": "GSTR-9C ↔ Books",
        "short_title": "GSTR-9C vs Books",
        "category": "annual",
        "category_label": "Annual & Audit Reconciliation",
        "level": "summary",
        "file1_label": "Audited Balance Sheet & P&L",
        "file2_label": "GSTR-9C Statement",
        "financial_metric_label": "GSTR-9C Reconciliation Variance",
        "party_label": "Ledger",
        "parties_label": "Audit Heads",
    },
}

def get_recon_metadata(recon_type: str) -> Dict[str, Any]:
    return RECONCILIATION_TYPES.get(recon_type, RECONCILIATION_TYPES["gstr2b_pr"])
